language: node_js
node_js:
  - "node"
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm ci
script:
  - npm run build
  - istanbul cover node_modules/jasmine/bin/jasmine.js
after_success:
  - codecov
