language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install -g istanbul
  - npm install
script:
  - npm run build
  - npm test
  - istanbul cover node_modules/jasmine/bin/jasmine.js
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
